force-app/main/default/objects/Card_Service__c/Card_Service__c.object-meta.xml
<CustomObject>
    <label>Card Service</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Card Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Card Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Card_Service__c/fields/ATM_Fee_in_other_currencies__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee_in_other_currencies__c</fullName>
    <label>ATM Fee in other currencies</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Card_Service__c/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <label>Card Replacement Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Card_Service__c/fields/Cost_per_Calendar_Month__c.field-meta.xml
<CustomField>
    <fullName>Cost_per_Calendar_Month__c</fullName>
    <label>Cost per Calendar Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Card_Service__c/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Card_Service__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Card Services</relationshipLabel>
    <relationshipName>Card_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Home_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <masterLabel>Home Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProductInfoControllerTest.cls
@isTest
public with sharing class ProductInfoControllerTest {
    private static Decimal COST_PER_MONTH = 1;
    private static Double ATM_FEE = 1;
    private static Decimal REPLACEMENT_COST = 1;
    @TestSetup
    static void setup(){
        Product2 stdProd = new Product2(
            Name = 'Standard Test',
            IsActive = true
        );
        insert stdProd;

        Contact contactSuccess = new Contact(
            LastName = 'Test Success Contact',
            Product__c = stdProd.Id,
            Home_Country__c = Constants.HOME_COUNTRY_DE
        );
        Contact contactWithoutMatchingCountry = new Contact(
            LastName = 'Test Contact Without Matching Card Service Country',
            Product__c = stdProd.Id,
            Home_Country__c = Constants.HOME_COUNTRY_FR
        );
        Contact contactWithMissingFields = new Contact(
            LastName = 'Test Contact Without Product'
        );
        insert new List<Contact>{
            contactSuccess, contactWithoutMatchingCountry, contactWithMissingFields
        };

        Case caseSuccess = new Case(
            Origin = 'Email',
            ContactId = contactSuccess.Id
        );
        Case casecontactWithMissingFields = new Case(
            Origin = 'Email',
            ContactId = contactWithMissingFields.Id
        );
        Case caseContactWithoutMatchingCountry = new Case(
            Origin = 'Email',
            ContactId = contactWithoutMatchingCountry.Id
        );
        Case caseWithoutContact = new Case(
            Origin = 'Email'
        );
        insert new List<Case>{
            caseSuccess, casecontactWithMissingFields,
            caseContactWithoutMatchingCountry, caseWithoutContact
        };

        Card_Service__c cardServiceSuccess = new Card_Service__c(
            Product__c = stdProd.Id,
            Home_Country__c = Constants.HOME_COUNTRY_DE,
            Cost_per_Calendar_Month__c = COST_PER_MONTH,
            ATM_Fee_in_other_currencies__c = ATM_FEE,
            Card_Replacement_Cost__c = REPLACEMENT_COST
        );
        insert cardServiceSuccess;
    }

    @isTest
    static void testGetProductInfoPositive() {
        Id productId = [SELECT Id FROM Product2 LIMIT 1].Id;
        Id successfulCaseId = [
            SELECT Id
            FROM Case
            WHERE Contact.Home_Country__c = :Constants.HOME_COUNTRY_DE
                AND Contact.Product__c = :productId
            LIMIT 1
        ].Id;

        Map<Id, Card_Service__c> cardServices = new Map<Id, Card_Service__c>([
            SELECT Id, Home_Country__c, Product__r.Name, Cost_per_Calendar_Month__c,
                ATM_Fee_in_other_currencies__c, Card_Replacement_Cost__c
            FROM Card_Service__c
            WHERE Product__c = :productId
                AND Home_Country__c = :Constants.HOME_COUNTRY_DE
        ]);

        Test.startTest();
        List<ProductInfoController.ProductInfoWrapper> result =
            ProductInfoController.getProductInfo(successfulCaseId);

        for (ProductInfoController.ProductInfoWrapper resultWrapper : result) {
            Card_Service__c cardService = cardServices.get(resultWrapper.cardServiceId);
            System.assertEquals(resultWrapper.productName, cardService.Product__r.Name, 'Product Name should be the same');
            System.assertEquals(resultWrapper.homeCountry, cardService.Home_Country__c, 'Home Country should be the same');
            for (ProductInfoController.ProductInfoFeatureField featureField : resultWrapper.featureFields) {
                System.assertEquals(featureField.value, cardService.get(featureField.apiName),
                    featureField.label + ' should be the same');
            }
        }
        Test.stopTest();
    }

    @isTest
    static void testGetProductInfoContactWithoutMatchingCardService() {
        Id productId = [SELECT Id FROM Product2 LIMIT 1].Id;
        Id caseId = [
            SELECT Id
            FROM Case
            WHERE Contact.Home_Country__c = :Constants.HOME_COUNTRY_FR
                AND Contact.Product__c = :productId
            LIMIT 1
        ].Id;

        Test.startTest();
        List<ProductInfoController.ProductInfoWrapper> result =
            ProductInfoController.getProductInfo(caseId);
        assertErrorWrapper(result, Constants.PRODUCT_INFO_ERROR_NO_PRODUCTS_FOR_CONTACT);
        Test.stopTest();
    }

    @isTest
    static void testGetProductInfoContactWithMissingFields() {
        Id contactId = [
            SELECT Id
            FROM Contact
            WHERE Home_Country__c = NULL
                AND Product__c = NULL
            LIMIT 1].Id;
        Id caseId = [
            SELECT Id
            FROM Case
            WHERE ContactId = :contactId
            LIMIT 1
        ].Id;

        Test.startTest();
        List<ProductInfoController.ProductInfoWrapper> result =
            ProductInfoController.getProductInfo(caseId);
        assertErrorWrapper(result, Constants.PRODUCT_INFO_ERROR_CONTACT_FIELDS_MISSING);
        Test.stopTest();
    }

    @isTest
    static void testGetProductInfoCaseWithoutContact() {
        Id caseId = [
            SELECT Id
            FROM Case
            WHERE ContactId = NULL
            LIMIT 1
        ].Id;

        Test.startTest();
        List<ProductInfoController.ProductInfoWrapper> result =
            ProductInfoController.getProductInfo(caseId);
        assertErrorWrapper(result, Constants.PRODUCT_INFO_ERROR_CONTACT_MISSING);
        Test.stopTest();
    }

    private static void assertErrorWrapper(List<ProductInfoController.ProductInfoWrapper> wrappers, String errorMessage) {
        System.assertEquals(wrappers.size(), 1, 'Should be only 1 wrapper (with error)');
        System.assert(wrappers[0].hasError, 'Shoud be error wrapper');
        System.assertEquals(wrappers[0].errorMessage, errorMessage,
            'Error messages should be the same');
    }
}