force-app/main/default/objects/Card_Service__c/Card_Service__c.object-meta.xml
<CustomObject>
    <label>Card Service</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Card Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Card Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Card_Service__c/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Card_Service__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Card Services</relationshipLabel>
    <relationshipName>Card_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Home_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <masterLabel>Home Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Constants.cls
public with sharing class Constants {
    public static String PRODUCT_INFO_ERROR_NO_PRODUCTS_FOR_CONTACT = System.Label.Product_Info_No_Products_for_Contact;
    public static String PRODUCT_INFO_ERROR_CONTACT_FIELDS_MISSING = System.Label.Product_Info_Contact_fields_are_missing;
    public static String PRODUCT_INFO_ERROR_CONTACT_MISSING = System.Label.Product_Info_No_Contact_for_Current_Case;

    public static String CONTACT_REST_ERROR_NO_UUIDS_PROVIDED = System.Label.Contact_Info_Error_No_UUIDs_Provided;
    public static String CONTACT_REST_ERROR_NO_CONTACTS_FOUND = System.Label.Contact_Info_Error_No_Contacts_Found;

    public static String PRODUCT_INFO_FIELD_SET_NAME = 'Product_Information';

    public static String CARD_SERVICE_API_NAME = 'Card_Service__c';

    public static String CONTACT_FIELD_API_NAME_HOME_COUNTRY = 'Home_Country__c';
    public static String CONTACT_FIELD_API_NAME_PRODUCT = 'Product__c';

    public static String HOME_COUNTRY_DE = 'DE';
    public static String HOME_COUNTRY_FR = 'FR';

    public static String URL_PARAM_UUIDS = 'uuids';
}