force-app/main/default/objects/Card_Service__c/Card_Service__c.object-meta.xml
<CustomObject>
    <label>Card Service</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Card Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Card Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Card_Service__c/fields/ATM_Fee_in_other_currencies__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee_in_other_currencies__c</fullName>
    <label>ATM Fee in other currencies</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Card_Service__c/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <label>Card Replacement Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Card_Service__c/fields/Cost_per_Calendar_Month__c.field-meta.xml
<CustomField>
    <fullName>Cost_per_Calendar_Month__c</fullName>
    <label>Cost per Calendar Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Card_Service__c/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Card_Service__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Card Services</relationshipLabel>
    <relationshipName>Card_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Home_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <masterLabel>Home Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProductInfoController.cls
public with sharing class ProductInfoController {
	@AuraEnabled
	public static List<ProductInfoWrapper> getProductInfo(String caseId) {
		List<ProductInfoWrapper> wrappers = new List<ProductInfoWrapper>();
		try {
			Case case = [
				SELECT Contact, Contact.Product__c, Contact.Home_Country__c
				FROM Case
				WHERE Id = :caseId
			];

			if (case.Contact != null && case.Contact.Product__c != null && case.Contact.Home_Country__c != null) {
				List<Card_Service__c> cardServices = [
					SELECT
						Id, Product__r.Name, Home_Country__c, CurrencyIsoCode, Cost_per_Calendar_Month__c, ATM_Fee_in_other_currencies__c, Card_Replacement_Cost__c
					FROM Card_Service__c
					WHERE
						Product__c = :case.Contact.Product__c
						AND Home_Country__c = :case.Contact.Home_Country__c
				];

				if (!cardServices.isEmpty()) {
					for (Card_Service__c cardService : cardServices) {
						wrappers.add(new ProductInfoWrapper(cardService));
					}
				} else {
					wrappers.add(getErrorWrapper(Constants.PRODUCT_INFO_NO_PRODUCTS_FOR_CONTACT));
				}
			} else {
				wrappers.add(getErrorWrapper(Constants.PRODUCT_INFO_CONTACT_FIELDS_MISSING));
			}
		} catch (Exception e) {
			wrappers.add(getErrorWrapper(e.getMessage()));
		}
		return wrappers;
	}

	private ProductInfoWrapper getErrorWrapper(String errorMessage) {
		ProductInfoWrapper wrapper = new ProductInfoWrapper();
		wrapper.hasError = true;
		wrapper.errorMessage = errorMessage;
		return wrapper;
	}

	private List<Schema.FieldSetMember> getFieldsFromFieldSet(String objectName, String fieldSetName) {
		return Type.forName(objectName).newInstance().getDescribe().FieldSets.getMap().get(fieldSetName);
	}

	public class ProductInfoWrapper {
		public ProductInfoWrapper() {}
		public ProductInfoWrapper(Card_Service__c cardService) {
            this.productId = cardService.Id;
			this.productName = cardService.Product__r.Name;
			this.homeCountry = cardService.Home_Country__c;
			this.currencyIsoCode = cardService.CurrencyIsoCode;
			this.costPerMonth = cardService.Cost_per_Calendar_Month__c;
			this.atmFeeInOtherCurrencies = cardService.ATM_Fee_in_other_currencies__c;
			this.cardReplacementCost = cardService.Card_Replacement_Cost__c;
		}

        @AuraEnabled
        public Id productId {get; set;}
		@AuraEnabled
		public String productName {get; set;}
		@AuraEnabled
		public String homeCountry {get; set;}
		@AuraEnabled
		public String currencyIsoCode {get; set;}
		@AuraEnabled
		public Decimal costPerMonth {get; set;}
		@AuraEnabled
		public Decimal atmFeeInOtherCurrencies {get; set;}
		@AuraEnabled
		public Decimal cardReplacementCost {get; set;}
		@AuraEnabled
		public Boolean hasError {get; set;}
		@AuraEnabled
		public String errorMessage {get; set;}
	}
}